### ISSUE TITLE
Data Updates/Enhancements

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#159]
Short term:
- [ ] Finish Trail differentiation (#128)
- [ ] La Grange / LaGrange?
- [ ] Maintenance Division data QA (Robin) (#136 for #62)

Recreation:
- [ ] Birding hotspot QA (Jim P.) (#114)
- [ ] Fishing map PDFs (#110)

After Trail Style Guide: (for #107)
- [ ] Trail difficulty
- [ ] Trail detailed surface (asphalt, stone, mowed, dirt)
- [ ] Average width
- [ ] Accessibility
- [ ] Nature Center Trails? (Single color, map available at Nature Center?)

Accessibility (Mike M.):
- [ ] Parking
- [ ] Trails
- [ ] Buildings
- [ ] Picnic Groves/Shelters
