### ISSUE TITLE
Web app improvements/enhancements

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#160]
- [ ] Advanced filtering (#148)
- [ ] Translation (Use Google Translate?) (#152)
- [ ] Search (mis)spelling, fuzzy string search (#141)
- [ ] Provide legitimate alternative version that meets accessibility guidelines (AKA new fpdcc.com, Q4 2017) (#124)
- [ ] Refine sign/activity icon sizes at different zoom levels (especially mobile) (#106)

**Comment by shua123** [comment]
Re-opening the individual issues and closing this. It is easy to track issues when they are separated.  Grouping can be done using Milestones, Projects, tags, etc.
